name: Lint Python scripts
on: [push, workflow_dispatch]
jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run ruff lint
        uses: astral-sh/ruff-action@v1
        with:
          changed-files: "true"